documentation:
  - any: [ '**/*.md' ]

infrastructure:
  - any: [ 'Dockerfile', 'helmfile.yaml', 'skaffold.yaml', 'docker-compose.yml', '**/*.tf' ]

frontend:
  - any: [ 'modules/javascript/**/*', '!modules/javascript/Dockerfile' ]

backend:
  - any: [ 'modules/php/**/*', 'modules/java/**/*', 'modules/ruby/**/*', 'modules/python/**/*', '!modules/*/Dockerfile' ]

