FROM ubuntu:latest

RUN apt-get update && apt-get install --yes curl && \
    curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - &&\
    apt-get install -y nodejs

WORKDIR /project

COPY src/app.js src/app.js

ENTRYPOINT ["node","src/app.js"]

CMD ["a"]