name: Docker build and push

on:
  pull_request:
    paths:
      - modules/**/*
    branches:
      - 'latest'

jobs:
  javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: modules/javascript
          push: true
          tags: ghcr.io/hive-school/course-devops:javascript

  php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: modules/php
          push: true
          tags: ghcr.io/hive-school/course-devops:php
