name: Label PR
on:
  - pull_request_target
jobs:
  triage:
    name: Apply labels to pull request
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
